### ISSUE TITLE
Quantum Mach-Zehnder interferometer

### ISSUE THREAD

**Issue by amartinfer** [qiskit-community/qiskit-hackathon-bilbao-19#13]
# Abstract
One of the milestones of quantum mechanics is Bohr’s complementarity principle. It states that a single quantum can exhibit a particlelike or a wavelike behavior, but never both at the same time. These are mutually exclusive and complementary aspects of the quantum system. This means that we need distinct experimental arrangements in order to measure the particle or the wave nature of a physical system. One of the most known representations of this principle is the single-photon Mach-Zehnder interferometer. When the interferometer is closed, an interference pattern is observed (quantum wavelike behaviour), while if it is open, the photon behaves like a particle. In this project, we want you to analyze the quantum version of this principle by means of an interferometer that is in a quantum superposition of being closed and open, and confirm that we can indeed measure both aspects of the system with the same experimental apparatus. More specifically, we observe with a single apparatus the interference between the particle and the wave aspects of a quantum system.

# Members

 - Qiskit Coach: 

# Deliverable

# GitHub repo

**Comment by marinakb2** [comment]
I'm Marina Cabedo Olaya, this project is my 'priority 2'.

**Comment by manuelgpda** [comment]
My name is Manuel García Pérez de Algaba and I would like to join this project with priority 2.
