### ISSUE TITLE
Efficient Quantum Tomography for detecting entanglement

### ISSUE THREAD

**Issue by amartinfer** [qiskit-community/qiskit-hackathon-bilbao-19#14]
# Abstract
Suppose a salesman comes to you claiming that he has a 100-qubit quantum device that can create entanglement between all the qubits. How can you verify his claim? Surely, you can do quantum tomography, but that will be too expensive as up to now there is no full tomography for more than 10 qubits.

Questions that may be interesting to address: How many qubits can be verified as entangled at a given device? Can we entangle all qubits of a 20-qubit device? What about the 53-qubit device?

#Useful Resources
Quantum Overlapping Tomography publication: https://arxiv.org/abs/1908.02754
# Members

 - Qiskit Coach: 

# Deliverable

# GitHub repo

**Comment by manuelgpda** [comment]
My name is Manuel García Pérez de Algaba and I would like to join this project with priority 1.
