### ISSUE TITLE
Solving KenKen with the HHL algorithm

### ISSUE THREAD

**Issue by amartinfer** [qiskit-community/qiskit-hackathon-bilbao-19#16]
# Abstract
KenKen, like Sudoku, is a combinatorial number-placement puzzle. The objective is to fill a n×n grid with integers from 1 to n so that no digit appears more than once in any row or any column. Additionally, KenKen grids are divided into heavily outlined groups of cells –– often called “cages” –– and the numbers in the cells of each cage must produce a certain “target” number when combined using a specified mathematical operation (addition, subtraction, multiplication or division). [Source: https://en.wikipedia.org/wiki/KenKen]
By writing all the conditions of a KenKen problem as  lineal equations, you could solve KenKen problems using the HHL algorithm implemented in IBM’s quantum simulator. What is the largest grid that you can solve?

Tips: 
-Use a total sum equation for every row and column instead of the usual KenKen restriction (e.g., on a 3x3 grid, every row and column must add to 6).
-Restrict your KenKen problem to addition and subtraction operations.
-Make sure that the determinant of your matrix is not zero before running your algorithm! To do this, you may want to use more than n equations and merge some on a single row of your matrix. 

# Useful Resources
 Qiskit HHL tutorial: https://github.com/Qiskit/qiskit-iqx-tutorials/blob/master/qiskit/advanced/aqua/linear_systems_of_equations.ipynb

# Members

 - Qiskit Coach: 
# Deliverable

# GitHub repo

**Comment by juan-dev-santos** [comment]
Juan Santos - Priority 2 (I´m a programmer with low knowledge on quantum computing)

**Comment by ilarburu** [comment]
Iker Unai Larburu - Priority 2 (I'm also a programmer with low knowledge on quantum)

**Comment by unaielejaga** [comment]
Unai Elejaga - Priority 2 Programmer

**Comment by sergisanchezprieto** [comment]
sergio sanchez prioridad 2

**Comment by eneko98** [comment]
Eneko Valero priority 2

**Comment by PirisCaballero** [comment]
Aitor Piris Caballero - prioridad 2 programador

**Comment by erikberter** [comment]
Erik Terres Escudero. Priority 2 (Math and programming)

**Comment by ilarburu** [comment]
Repositorio : https://github.com/ilarburu/hackathon-bilbao-2019.git
