### ISSUE TITLE
Play CHSH game

### ISSUE THREAD

**Issue by delapuente** [qiskit-community/qiskit-hackathon-bilbao-19#2]
# Abstract
The CHSH game is a collaborative game where 2 players should come up with an strategy for winning a game in most of the cases after several plays. The best classical strategy can only win this game with probability 75%. However, using entangled qubits and non-classical correlations, it is possible to win with probability ~85%.

# Description 
- Check [Lecture 13, Tues Feb 28: Hidden Variables,Bell’s Inequality](https://www.scottaaronson.com/qclec/13.pdf) for a description of the game (and [the next chapter](https://www.scottaaronson.com/qclec/14.pdf), for a solution).
- Check [The CHSH Game: Lecture 7 of Quantum Computation at CMU](https://www.youtube.com/watch?v=1nh-pjxnM4I&t=605s) for a video explaining the HLSL game (slides in [PDF](https://www.cs.cmu.edu/~odonnell/quantum18/lecture07.pdf)).
- Check [Quirk Online Quantum Simulator](https://algassert.com/quirk#circuit={%22cols%22:[[%22H%22],[%22%E2%97%A6%22,1,1,1,%22X%22],[%22X^-%C2%BC%22],[%22%E2%80%A6%22,%22%E2%80%A6%22,%22%E2%80%A6%22,%22%E2%80%A6%22,%22%E2%80%A6%22],[%22~da85%22,%22~5s2n%22,1,%22~5s2n%22,%22~ahov%22],[1,%22H%22,1,%22H%22],[1,%22Measure%22,1,%22Measure%22],[%22X^%C2%BD%22,%22%E2%80%A2%22],[1,1,1,%22%E2%80%A2%22,%22X^%C2%BD%22],[%22Measure%22,1,1,1,%22Measure%22],[%22%E2%80%A6%22,%22%E2%80%A6%22,%22%E2%80%A6%22,%22%E2%80%A6%22,%22%E2%80%A6%22],[1,%22%E2%80%A2%22,%22X%22,%22%E2%80%A2%22],[%22%E2%80%A2%22,1,%22X%22],[1,1,%22X%22,1,%22%E2%80%A2%22],[1,1,%22Chance%22],[1,1,%22~q6e%22]],%22gates%22:[{%22id%22:%22~da85%22,%22name%22:%22Alice%22,%22matrix%22:%22{{1,0},{0,1}}%22},{%22id%22:%22~ahov%22,%22name%22:%22Bob%22,%22matrix%22:%22{{1,0},{0,1}}%22},{%22id%22:%22~5s2n%22,%22name%22:%22Referee%22,%22matrix%22:%22{{1,0},{0,1}}%22},{%22id%22:%22~q6e%22,%22name%22:%22Win?%22,%22matrix%22:%22{{1,0},{0,1}}%22}]}) for an implementation of the quantum circuit.

# Members

 - @githubhandle 
 - @githubhandle - Slack: `@slackhandle` email: `example@example.com`
 - Qiskit Coach: @delapuente 

# Deliverable
A PyGame/Mobile App/Website or similar allowing the player to experience and compare the classical and quantum strategies by changing the decisions made during the classical game, and the rotation angles for the basis during the quantum version.

# GitHub repo

**Comment by AntonioCobosLuque** [comment]
Hi, I'm Antonio Cobos and I'm interested in this proyect (priority 2)
