### ISSUE TITLE
Port MicroQiskit to a new language

### ISSUE THREAD

**Issue by quantumjim** [qiskit-community/qiskit-hackathon-bilbao-19#20]
# Abstract
[MicroQiskit](https://github.com/quantumjim/MicroQiskit/blob/master/README.md) is essentially a trial version of Qiskit, which is made available in languages other than Python 3. It contains all the basic features of writing and simulating quantum programs in Qiskit, all implemented in a minimal amount of code (~100 lines for the Python2/MicroPython/CircuitPython version). This could be ported to a new language, and a quick demo project could be made.

# Description

Current Versions:
* Python2/MicroPython/CircuitPython.
* C++ (working but unfinished).

Suggestions for ports:
* C# (to be compatible with Unity and GoDot)
* Lua (to be compatible with Minetest and Pico8)

# Members

 - @githubhandle 
 - @githubhandle - Slack: `@slackhandle` email: `example@example.com`
 - Qiskit Coach: @quantumjim (Coaching from afar. Available as 'James Wootton' on the Qiskit Slack. 

# Deliverable
A branch on the MicroQiskit repo with a working port.

# GitHub repo
github.com/quantumjim/MicroQiskit

**Comment by ilarburu** [comment]
Iker Unai Larburu - Priority 2

**Comment by bruno-sm** [comment]
Bruno Santidrian - Priority 1

**Comment by Serux** [comment]
Sergio Chico - Priority 1

**Comment by ilarburu** [comment]
Iker Unai Larburu - Priority 1
