### ISSUE TITLE
Easy peasy Shor algorithm

### ISSUE THREAD

**Issue by amartinfer** [qiskit-community/qiskit-hackathon-bilbao-19#3]
# Abstract
What’s the biggest integer you can factorize using Shor’s algorithm and the real IBM quantum processor?

# Useful resources
https://leftasexercise.com/2019/03/11/factoring-integers-on-a-quantum-computer-with-qiskit/

# Members
1.
2.
3.
4.
5.

 - Qiskit Coach: 

# Deliverable

# GitHub repo

**Comment by FernanadoMachoHernantes1** [comment]
Fernando Macho Hernantes

**Comment by arg188** [comment]
Hi, I am Álvaro and I have previous knowledge about this Algorithm. I am interested in this project. Priorirty 1
