### ISSUE TITLE
Quantum circuits optimization using quantum gates identities. Simulator vs reality

### ISSUE THREAD

**Issue by amartinfer** [qiskit-community/qiskit-hackathon-bilbao-19#5]
# Abstract
Qiskit has a built-in optimization tool that allows the quantum programmer to design any quantum circuit without taking into account the experimental layout of the quantum processor on which she/he is going to run the quantum program.
Using quantum gates identities, optimize any quantum circuit of your choice and compare your results with the qiskit optimized version of the same circuit. Do this for both the classical simulator and the real IBM’s quantum processors. Do you notice any difference between the simulation and the real implementation? Do you have any clue of what is happening? 

# Members

 - Qiskit Coach: 

# Deliverable

# GitHub repo

**Comment by BedialaunetaDani** [comment]
Daniel Bedialauneta, priority 2

**Comment by jorloru** [comment]
I'm Jorge López Rubio, priority 2

**Comment by ghost** [comment]
Alvaro Bermjillo priority 2

**Comment by fernandezander98** [comment]
Ander Fernandez, priority 2

**Comment by danidc98** [comment]
Daniel del Canto, priority 2
