### ISSUE TITLE
Maximally entangled states, how big can you make them?

### ISSUE THREAD

**Issue by amartinfer** [qiskit-community/qiskit-hackathon-bilbao-19#8]
# Description 
The quantum state 1/sqrt(2)·(|00>+|11>)is a maximally entangled 2-qubit state. It is called a Bell state, or a 2-qubit GHZ (Greenberger-Horne-Zeilinger) state. The state  
1/sqrt(2)·(|000>+|111>)is a 3-qubit GHZ state, and so on. What is the largest GHZ state that you can produce using the IBM quantum simulator? How does the fidelity of the output scale with the number of qubits on the real quantum processor?

Next level:
Can you produce 
a) W states (single-excitation states, like 1/sqrt(4)·(|1000>+|0100>+|0010>+|0001>)) and
b) cluster states (defined-parity states, like  1/sqrt(8)·(|0000>+|1100>+|1010>+|1001>+|0110>+|0101>+|0011>+|1111>)) )?
How do their fidelities scale up with the number of qubits on the real quantum processor?

# Useful Resources
https://quantumcomputing.stackexchange.com/questions/2258/how-to-implement-the-4-bell-states-on-the-ibm-q-composer

# Members

 - Qiskit Coach: 

# Deliverable

# GitHub repo

**Comment by Qcaria** [comment]
Carlos Munuera Javaloy, Priority 3
